### ISSUE TITLE
Improve the TO field

### ISSUE THREAD

**Issue by scottjenson** [scidsg/hushline-website#3]
Scott Jenson

**Who is the user?**
All users

**What's the problem being solved?**
Make it clearly WHO this tip is going to

**What are your proposed solution(s)?**
In general, make the TO field stronger so:
1) Increase the font size a few points
2) Increase the contrast (don't use gray font)
3) "hide" the keyID (This is important info but not relevant to most tipsters, consider a "Key" icon that when clicked, shows this information.

**Comment by glenn-sorrentino** [comment]
Updated using headline with To information
