### ISSUE TITLE
Better introduction prompt on the tip page

### ISSUE THREAD

**Issue by scottjenson** [scidsg/hushline-website#4]
**Requester:**
Scott Jenson

**Who is the user?**
All users

**What's the problem being solved?**
Make it clearer what this tipline is about

**What are your proposed solution(s)?**
One or both of the following options:
1. Allow for a prompt below the "HushLine" title that lets the admin say anything they want about this tip line.
2. Allow the prompt text in the text field to be modified

I expect 1 will be the clearest but will have a bigger visual impact on the page. 2 will be more subtle

**Comment by glenn-sorrentino** [comment]
Added bio, better headline, and a directory for more clarity
