### ISSUE TITLE
Change the text prompt

### ISSUE THREAD

**Issue by scottjenson** [scidsg/hushline-website#5]
**Requester:**
Scott Jenson

**What's the problem being solved?**
Current prompt: 
Please leave a contact method if you'd like a response...

**What are your proposed solution(s)?**
Suggested prompt:
Type your anonymous message here. If you want to be contacted, leave some way to get a hold of yourself.

The goal is to make it extra clear this is anonymous and to prompt more directly for a contact info if needed.

**Comment by glenn-sorrentino** [comment]
added a contact method field for more clarity.
