### ISSUE TITLE
Make the help text above the SUBMIT button in the tipline UI be clearer

### ISSUE THREAD

**Issue by scottjenson** [scidsg/hushline-website#6]
**Requester:**
Scott

**What's the problem being solved?**
The current tip is a bit soft and doesn't grab the user and make them feel safe

**What are your proposed solution(s)?**
Suggest the following text:
Hush Line allows anyone to send a message anonymously and safely. Everything is encrypted so no one else can see your message. [Click here](google.com) if you'd like to learn more.

Note the CLICK HERE link should NOT be hushline.app but a dedicated FAQ for tipsters (not admins!)

**Comment by glenn-sorrentino** [comment]
added more info around encryption hints
