### ISSUE TITLE
Who is HushLine for? page needs tightening

### ISSUE THREAD

**Issue by scottjenson** [scidsg/hushline-website#8]
**Requester:**
Scott Jenson

**What's the problem being solved?**
The page scrolls too much and over indexes on images (which are fine! they just take up too much space) In addition, it mixes the who with the how, getting into the RPi. Focus on who the users are and why they need it.

**What are your proposed solution(s)?**
![HushLine UX Comments (1)](https://github.com/scidsg/hushline-website/assets/1055674/eb1d1ab4-1ea0-4e8c-bf4a-5808b1d0bb14)

**Comment by glenn-sorrentino** [comment]
users more compact now.
