### ISSUE TITLE
Make the features section of hushline.app easier to parse

### ISSUE THREAD

**Issue by scottjenson** [scidsg/hushline-website#9]
**Requester:**
Scott Jenson

**What's the problem being solved?**
The current layout is a 2x3 grid of features of differing value. Break them up into pairs of 2 with a stronger wording. (the exact wording is TBD, the point here is to show the layout using the existing cards, just with a) some order (most important first) and a bit of clustering to people can glance/skip as needed.

![HushLine UX Comments (2)](https://github.com/scidsg/hushline-website/assets/1055674/d25fdd7a-4799-41c6-be48-0db30316178a)
![HushLine UX Comments (3)](https://github.com/scidsg/hushline-website/assets/1055674/69327197-9eef-4772-a13c-184f4bbe40dc)

**What are your proposed solution(s)?**

**Comment by glenn-sorrentino** [comment]
Old ticket, but good feedback and updated a while back.
